packages:
  - packages/*
catalog:
  '@babel/core': 7.28.0
  '@babel/preset-env': ^7.28.0
  '@types/babel__core': ^7.1.20
  '@types/babel__traverse': ^7.0.9
  '@types/node': ^24.0.15
  typescript: 5.8.3
  vitest: ^3.2.4
onlyBuiltDependencies:
  - esbuild
